### ISSUE TITLE
ArgoCD plugins as a sidecar

### ISSUE THREAD

**Issue by emouawad** [kubeshop/testkube-argocd#7]
The common practice is now using plugins as sidecars of the reposerver - https://argo-cd.readthedocs.io/en/stable/operator-manual/config-management-plugins/#register-the-plugin-sidecar

The helm chart also supports initContainers

Would it be possible for testkube to be used as a plugin sidecar container without having to patch the official image (slower upgrades - possible bugs)

**Comment by vsukhin** [comment]
thank you @emouawad let's us think about it a bit

**Comment by vsukhin** [comment]
for @TheBrunoLopes to analyse

**Comment by ypoplavs** [comment]
hello @emouawad!

We have update the documentation on how to use Testkube as a sidecar. Please try and let us know about the results:
https://testkube.io/blog/a-gitops-powered-kubernetes-testing-machine-with-argocd-and-testkube

**Comment by emouawad** [comment]
Great thanks!

Probably unrelated - but argocd still detecting out-of-sync on the tests that use test schedule (they generate cronjobs).
My guess we could tell argo to skip such checks for now - but it would be awesome without having to do such harcoded excludes by name or by type.

Is that something testkube can tackle - should i open another ticket to track this?
